players = [
  {
    'name': 'Christian Pulisic',
    'age': 24,
    'nation': 'USA',
    'salary': 650000,
    'number': 10,
    'preferred_foot': 'right',
    'position': 'Attacker',
    'skill_move': 'step over',
  },
  {
    'name': 'Tim Ream',
    'age': 35,
    'nation': 'USA',
    'salary': 120000,
    'number': 3,
    'preferred_foot': 'right',
    'position': 'Defender',
    'in_box': True,
  },
  {
    'name': 'Tyler Adams',
    'age': 23,
    'nation': 'USA',
    'salary': 750000,
    'number': 4,
    'preferred_foot': 'right',
    'position': 'Attacker',
    'skill_move': 'effective tackle',
  },
]